version: "3"

services:
  whisper:
    image: "whisper"
    build: ./whisper
    ports:
      - "80:5000"
      - "443:5000"
    volumes:
      - ./whisper:/app
    restart: always
    networks:
      - karaoke-services

  split-audio:
    image: "split-audio:latest"
    build: ./split
    volumes:
      - ./split/app.py:/var/task/app.py
      - ~/.aws:/root/.aws:ro
    restart: always
    ports:
      - "9000:8080"

networks:
  karaoke-services:
    driver: bridge